name: Django testing and deployment

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-20.04
    env:
      SECRET_KEY: ${{ secrets.SECRET }}
      DEBUG: "0"
      ALLOWED_HOSTS: ${{ secrets.ALLOWED }}
      ENGINE: ${{ secrets.DB_ENGINE }}
      USER: ${{ secrets.DB_USER }}
      PASSWORD: ${{ secrets.DB_PASSWORD }}
      NAME: ${{ secrets.DB_NAME }}
      HOST: ${{ secrets.DB_HOST }}
      PORT: ${{ secrets.DB_PORT }}
    services:
      postgres_db:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ env.NAME }}
          POSTGRES_USER: ${{ env.USER }}
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Проверяем репозиторий на наличие изменений
        uses: actions/checkout@v4

      - name: Установка python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: pip install -r requirements.txt
#        uses:  py-actions/py-dependency-install@v4
#        with:
#          path: "./requirements.txt"

      - name: Линтинг
        run: flake8 logistic/ --exclude logistic/migrations/

      - name: Тестирование
        run: python manage.py test
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: ${{ env.DEBUG }}
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_ENGINE: ${{ env.ENGINE }}
          DB_NAME: ${{ env.NAME }}
          DB_USER: ${{ env.USER }}
          DB_PASSWORD: ${{ env.PASSWORD }}
          DB_HOST: ${{ env.HOST }}
          DB_PORT: ${{ env.PORT }}
